### ISSUE TITLE
Ctrl+C triggers "Ticket copy"

### ISSUE THREAD

**Issue by tofi86** [davidegiacometti/redmine_shortcuts#1]
Hi,

thanks for the rgeat plugin.

I have a bug report: When pressing Ctrl+c to copy a text string from a page, the "Ticket copy" action get's triggered.

This should be prevented.

Thanks,
Tobias

**Comment by tofi86** [comment]
I fixed this and made a PullRequest: #2

Please merge and release this soon as a new version. Thanks!

**Comment by davidegiacometti** [comment]
Thank you @tofi86 
Code merged and released version [0.0.2](https://github.com/davidegiacometti/redmine_shortcuts/releases/tag/0.0.2)
