### ISSUE TITLE
Problem at login page

### ISSUE THREAD

**Issue by 6el-i** [davidegiacometti/redmine_shortcuts#11]
On the Redmine authorization page, the field of remembered logins "jumps" this happens 10 times (similar visual error behavior is observed only in FireFox and Safari).
Perhaps this is due to the parallel installation of the plugin Shortcuts and PlantUml, but I'm not sure.
Our engineer suggested such a solution, it's work:
--- redmine_shortcuts/assets/javascripts/view_layouts_base_body_bottom_questionmark.js  2021-06-03 21:08:20.171967086 +0000
+++ view_layouts_base_body_bottom_questionmark.js       2021-06-03 21:09:24.074637694 +0000
@@ -3,7 +3,9 @@
 $questionMarkModal = $('<div class="question-mark-modal"><span aria-label="Close" aria-role="button" class="question-mark--close"/></div>')
 $questionMarkModalRoot.append($questionMarkModal);
 $questionMarkModal.append('<iframe width="500px" height="500px" src="' + window.location.origin + '/redmine_shortcuts/help"></iframe>');
-$('body').append($questionMarkModalRoot);
+if ($('.controller-welcome').length) {
+$('body').append($questionMarkModalRoot);
+}
 $(document).on('keypress', function(e) {
   e = e || window.event;
   var charCode = e.keyCode || e.which;

**Comment by davidegiacometti** [comment]
Hi @6el-i 
Can you post a screenshot of the bug?
What is the version of Redmine?

**Comment by davidegiacometti** [comment]
Closing as "can't repro".
