### ISSUE TITLE
QuestionMark integration proposal

### ISSUE THREAD

**Issue by kporras07** [davidegiacometti/redmine_shortcuts#5]
Hi,
I've just started using this plugin and I really like it. I would like to propose a improvement and would like to know if this is something you'd be interested.

I would like that if user presses the "?" key, we get the help (pretty much what happens on Github out of any textarea). Would you be interested in adding integration with https://github.com/impressivewebs/QuestionMark.js to do this? If you agree, I could start working on this and submit a PR.

**Comment by kporras07** [comment]
Actually, not necessarily questionmark; I think it would be simpler to integrate simple js/jquery to invoke the help page in a modal when pressing ? key. I'll provide a PR for your consideration

**Comment by davidegiacometti** [comment]
PR merged and released in [0.4.0](https://github.com/davidegiacometti/redmine_shortcuts/releases/tag/0.4.0).
Thanks for contributing!
