### ISSUE TITLE
[feature] "Code" shortcut

### ISSUE THREAD

**Issue by pkonopelko** [davidegiacometti/redmine_shortcuts#8]
Hello @davidegiacometti,
Thank you for developing this plugin, I really like it and found it very useful!

The only thing I miss is a "Code" ![Screenshot 2020-12-02 at 3 22 31 PM](https://user-images.githubusercontent.com/4892057/100884810-37cdf680-34b2-11eb-9630-4d8ad445d7a6.png) shortcut. Would it be possible to add it as e.g. <kbd>Ctrl</kbd>/<kbd>Command</kbd>+<kbd>@</kbd> a.k.a. <kbd>Ctrl</kbd>/<kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>2</kbd>?

Thanks,
Piotr

**Comment by davidegiacometti** [comment]
Hi @pkonopelko 
Thank you for using this plugin!
I like this idea but I prefer to keep every editor shortcuts as **CTRL + KEY**
I think we can use the following:

- **CTRL + L** or **CTRL + K** for inline code ![image](https://user-images.githubusercontent.com/25966642/100921216-86908600-34dc-11eb-82c2-78124524307e.png)

- **CTRL + P** for preformatted text (lines of code) ![image](https://user-images.githubusercontent.com/25966642/100921284-9c05b000-34dc-11eb-9cc1-a9fc10c7576c.png)

**Comment by pkonopelko** [comment]
Hi @davidegiacometti,
Thanks for a prompt answer! I like <kbd>Ctrl</kbd>+<kbd>K</kbd> and I believe this one would be better for inline code since <kbd>Ctrl</kbd>+<kbd>L</kbd> is usually used to start editing the website URL in the browser's URL bar immediately, so grabbing it would cause a conflict with browser's shortcut here.

I'm not sure about <kbd>Ctrl</kbd>+<kbd>P</kbd> for preformatted text since it is usually another browser-wide shortcut for printing (similar conflict as above). What do you think about <kbd>Ctrl</kbd>+<kbd>/</kbd> for pre?

BTW, it probably would be great for the plugin to distinguish if selected text is already formatted and make it able to "unformat" it, but this would probably a bit bigger change than adding a new shortcut to the list, and it probably would need a separate issue / feature request. Just mentioning by the way as an idea which came up into my mind while playing with your plugin.

Best,
Piotr

**Comment by davidegiacometti** [comment]
> I'm not sure about `Ctrl + P` for preformatted text since it is usually another browser-wide shortcut for printing (similar conflict as above). What do you think about `Ctrl + /` for pre?

CTRL + P should't be a problem since the shortcut is detected only when the editor.
CTRL + U and CTRL + S have the same problem since are used for open the source code of the page and save the page.

> BTW, it probably would be great for the plugin to distinguish if selected text is already formatted and make it able to "unformat" it, but this would probably a bit bigger change than adding a new shortcut to the list, and it probably would need a separate issue / feature request. Just mentioning by the way as an idea which came up into my mind while playing with your plugin.

Of course! Unformat would be a nice feature but will require more time and since I am not using Redmine anymore I am not planning to work on it.
Open an issue and let's see if someone want to contribute.

**Comment by davidegiacometti** [comment]
Hi @pkonopelko 
I have just released version [0.5.0](https://github.com/davidegiacometti/redmine_shortcuts/releases/tag/0.5.0).

**Comment by pkonopelko** [comment]
Hi @davidegiacometti,
Sorry for lack of response earlier. I must have gotten distracted and didn't send the reply.

> CTRL + P should't be a problem since the shortcut is detected only when the editor.

Ahh, I see, no issue then :)

> Unformat would be a nice feature but will require more time and since I am not using Redmine anymore I am not planning to work on it.
> Open an issue and let's see if someone want to contribute.

> I have just released version [0.5.0](https://github.com/davidegiacometti/redmine_shortcuts/releases/tag/0.5.0).

That's great, thanks for such a fast release! I have just updated the plugin and got very positively surprised (since I updated and tested it first and then read the release notes) – you have also added a feature of undoing the formatting! It works so great – many, many thanks!

By the way, while testing the new release, it just came to my mind that perhaps <kbd>Ctrl</kbd>+<kbd>K</kbd> refers to "code" more than <kbd>Ctrl</kbd>+<kbd>L</kbd> and one could probably remember it with <kbd>L</kbd> easier than with <kbd>K</kbd> (since when you read _code_ out loud, it's actually read like _kode_). I just thought a moment about it and I have also seen a shortcut for formatting as "code" with <kbd>K</kbd> in other apps, like Telegram for example (it's <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd> there). What do you think about it?

Many thanks again for your time spent on that, I really appreciate it!

**Comment by pkonopelko** [comment]
Since it seems to be a very easy change, I could probably try to do it myself and make a PR for it if you prefer

**Comment by davidegiacometti** [comment]
I have finally decided to go for CTRL + L like line for inline code because I prefer this one.
If you want to customize the shortcut you can fork the plug-in since it's an easy change.

There are many people that have forked the plug-in and have changed some shortcuts.

**Comment by pkonopelko** [comment]
Hi Davide,
I understand and respect your decision – it's your code after all :)
Maybe I will do so or just get used to the one you like more, or – maybe the best – I'll ask my teammates what they actually prefer.

As a thank you for you awesome work I added Polish localization and reviewed the plugin in Redmine Plugins Directory.

**Comment by davidegiacometti** [comment]
Thank you for understanding and for the review! 😃 
I close the issue.
